export { default as Discussion } from './Discussion'
export type { DiscussionProps, IDiscussion, IDiscussionCreator } from './types'
export { CommentInput } from './CommentInput'
export type { CommentInputHandle, CommentInputProps } from './CommentInput'
export { CommentItem } from './CommentItem'
export type { CommentItemProps } from './CommentItem'
export { Avatar } from './Avatar'
export { DateDivider } from './DateDivider'
export { DEMO_CURRENT_USER, DEMO_FLAT_COMMENTS, DEMO_RESOURCE, DEMO_RESOURCE_ID } from './mockData'
export { demoResetStore } from './demoStore'
